# Generated by Django 4.2.1 on 2023-12-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
