# Generated by Django 4.2.1 on 2024-04-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PROCEEDING', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verbal_Fluency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('perseverations', models.IntegerField()),
                ('intrusions', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Towers_Hanoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movements_first', models.IntegerField()),
                ('time_first', models.IntegerField()),
                ('type_1_error_first', models.IntegerField()),
                ('type_2_error_first', models.IntegerField()),
                ('total_error_first', models.IntegerField()),
                ('movements_second', models.IntegerField(null=True)),
                ('time_second', models.IntegerField(null=True)),
                ('type_1_error_second', models.IntegerField(null=True)),
                ('type_2_error_second', models.IntegerField(null=True)),
                ('total_error_second', models.IntegerField(null=True)),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Substraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes_a', models.IntegerField()),
                ('mistakes_a', models.IntegerField()),
                ('time_a', models.IntegerField()),
                ('successes_b', models.IntegerField(null=True)),
                ('mistakes_b', models.IntegerField(null=True)),
                ('time_b', models.IntegerField(null=True)),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Stroop_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('stroop_errors', models.IntegerField()),
                ('non_stroop_errors', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Stroop_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('stroop_errors', models.IntegerField()),
                ('non_stroop_errors', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Signaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('perseverations', models.IntegerField()),
                ('omissions', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Semantic_Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_categories', models.IntegerField()),
                ('specific_average', models.IntegerField()),
                ('functional_categories', models.IntegerField()),
                ('functional_average', models.IntegerField()),
                ('abstract_categories', models.IntegerField()),
                ('abstract_average', models.IntegerField()),
                ('total_categories', models.IntegerField()),
                ('total_average', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Sayings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essays_first_list', models.IntegerField()),
                ('order_errors_first', models.IntegerField()),
                ('perseverations_first', models.IntegerField()),
                ('intrusions_first', models.IntegerField()),
                ('essays_second_list', models.IntegerField()),
                ('order_errors_second', models.IntegerField()),
                ('perseverations_second', models.IntegerField()),
                ('intrusions_second', models.IntegerField()),
                ('essays_third_list', models.IntegerField(null=True)),
                ('order_errors_third', models.IntegerField(null=True)),
                ('perseverations_third', models.IntegerField(null=True)),
                ('intrusions_third', models.IntegerField(null=True)),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Metamemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrusions', models.IntegerField()),
                ('perseverations', models.IntegerField()),
                ('positive_errors', models.IntegerField()),
                ('negative_errors', models.IntegerField()),
                ('total_errors', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Labyrinths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touch', models.IntegerField()),
                ('cross', models.IntegerField()),
                ('caught', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Cards_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('percentage_risk_cards', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('first_question', models.CharField(max_length=30)),
                ('second_question', models.CharField(max_length=30)),
                ('third_question', models.CharField(max_length=30)),
                ('fourth_question', models.CharField(max_length=30)),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('perseverations', models.IntegerField()),
                ('deferred_perseverations', models.IntegerField()),
                ('maintenance_error', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
        migrations.AddField(
            model_name='banfe',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.cortex'),
        ),
        migrations.AddField(
            model_name='banfe',
            name='proceeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROCEEDING.proceeding'),
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successes', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('time', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
    ]
