# Generated by Django 4.2.1 on 2024-04-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BANFE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visuospatial_Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_errors', models.IntegerField()),
                ('substitution_errors', models.IntegerField()),
                ('perseverations', models.IntegerField()),
                ('maximum_sequence', models.IntegerField()),
                ('banfe_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANFE.banfe')),
            ],
        ),
    ]
