# Generated by Django 4.2.1 on 2024-04-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANFE', '0002_visuospatial_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banfe',
            name='area',
        ),
        migrations.AddField(
            model_name='banfe',
            name='areas',
            field=models.ManyToManyField(to='BANFE.cortex'),
        ),
    ]
