# Generated by Django 4.2.1 on 2024-04-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANFE', '0003_remove_banfe_area_banfe_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banfe',
            old_name='areas',
            new_name='area',
        ),
    ]
