# Generated by Django 4.2.1 on 2024-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANFE', '0004_rename_areas_banfe_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards_game',
            name='percentage_risk_cards',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='semantic_classification',
            name='total_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
