# Generated by Django 4.2.1 on 2024-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANFE', '0005_alter_cards_game_percentage_risk_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semantic_classification',
            name='abstract_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='semantic_classification',
            name='functional_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='semantic_classification',
            name='specific_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
