# Generated by Django 5.0.4 on 2024-04-24 23:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('BANFE', '0006_alter_semantic_classification_abstract_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayings',
            name='successes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
