from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=255)

class State(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

class Municipality(models.Model):
    name = models.CharField(max_length=255)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

class Proceeding(models.Model):
    name= models.CharField(max_length=40)
    first_last_name = models.CharField(max_length=30)
    second_last_name= models.CharField(max_length=30)
    dateEval = models.DateField()
    dateNac = models.DateField()
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=False)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True, blank=True)
    municipality = models.ForeignKey(Municipality, on_delete=models.SET_NULL, null=True, blank=True)
    language = models.CharField(max_length=30)
    indigenous_language = models.CharField(max_length=30)
    talk_other_language = models.BooleanField()
    other_languages = models.CharField(max_length=40, null=True, blank=True)
    gender = models.CharField(max_length=10)
    scholarship = models.CharField(max_length=30)
    years_study = models.IntegerField()
    laterality = models.CharField(max_length=12)
    occupation = models.CharField(max_length=30)
    instrument = models.CharField(max_length=10)
    time_instrument = models.CharField(max_length=15, null=True, blank=True)
    hobbies = models.CharField(max_length=24)
    time_hobbies = models.CharField(max_length=24, null=True, blank=True)
    civil_status = models.CharField(max_length=12)
    religion = models.CharField(max_length=18)
    mother_scholarship = models.CharField(max_length=30)
    father_scholarship = models.CharField(max_length=30)
    referred_by = models.CharField(max_length=60)
    phone_number = models.CharField(max_length=14)
    reason_consultation = models.CharField(max_length=60)
    alert_status = models.CharField(max_length=60)
    medicine = models.CharField(max_length=60)
    other_exams = models.CharField(max_length=60)
    medical_history = models.CharField(max_length=400, null=True, blank=True)
    hyperthension = models.BooleanField()
    time_hyperthension = models.CharField(max_length=16, null=True, blank=True)
    pulmonary_diseases = models.BooleanField()
    time_pulmonary_diseases = models.CharField(max_length=16, null=True, blank=True)
    alcoholism = models.BooleanField()
    time_alcoholism = models.CharField(max_length=16, null=True, blank=True)
    drugs = models.BooleanField()
    time_drugs = models.CharField(max_length=16, null=True, blank=True)
    decrease_senses = models.BooleanField()
    time_decrease_senses = models.CharField(max_length=16, null=True, blank=True)
    craniocerebral_trauma = models.BooleanField()
    time_craniocerebral_trauma = models.CharField(max_length=16, null=True, blank=True)
    diabetes = models.BooleanField()
    time_diabetes = models.CharField(max_length=16, null=True, blank=True)
    hypothyroidism = models.BooleanField()
    time_hypothyroidism = models.CharField(max_length=16, null=True, blank=True)
    strokes = models.BooleanField()
    time_strokes = models.CharField(max_length=16, null=True, blank=True)
    others_diseases = models.BooleanField()
    details_others_diseases = models.CharField(max_length=50, null=True, blank=True)    
    user = models.ForeignKey(User, on_delete=models.CASCADE)

