# Generated by Django 5.0.4 on 2024-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROCEEDING', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceeding',
            name='father_scholarship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='mother_scholarship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
